method: sca
output_size: 2
loss_func: CE
n_epochs: 50
num_anchors: 0
batch_size: 1024
n_z: 1
lsmooth: 0.2
data: handwritten
view1_idx: 2
view2_idx: 3
n_test: 256
n_repeats: 10
seed: 42
results_dir: results
orthogonal_w: 1.0 # 0.1
encoder_lr: 0.01 # 0.001
discr_lr: 0.0001
